title: Café com feminismo
description: Website oficial do Café com feminismo

url: https://samuelgebing.github.io/cafecomfeminismo.github.io/
baseurl: "https://samuelgebing.github.io/cafecomfeminismo.github.io/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Início
    url: /index.html
  - title: Todos os artigos
    url: /articles
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact

social:
  github: cafecomfeminismo
  twitter: cafecomfeminismo
  facebook: cafecomfeminismo
  email: samu.gebing@gmail.com

google_analytics: "GOOGLE"
